### ISSUE TITLE
Makefiles of our libraries do not raise errors

### ISSUE THREAD

**Issue by GuillaumeGen** [Deducteam/Dedukti#39] opened 2018-02-14 10:13 UTC
The makefiles of our libraries do not raise error, hence if an error occurs during the type-checking of a library, Travis will not consider this build as failed.

**Comment by rlepigre** [comment] 2018-02-16 16:06
The problem is actually in the shell script used by Travis. This should be fixed by 29cd7703598a655a8fa3de90ac148b376e80cbe2.

**Closed by rlepigre** 2018-02-16 16:06 UTC
